version: "3.0"
services:
  postgres96:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin@123
      POSTGRES_USER: postgres



        #    command: >
        #      bash -c "apt-get update
        #      && apt-get -y install sudo
        #      && apt-get -y install software-properties-common
        #      && apt-get -y install postgis postgresql-9.6-postgis-2.3"
