version: "3.0"
services:
  pgdb:
    image: mdillon/postgis
    ports:
      - "5432:5432"
    environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASS: admin@123
#  springbootapp:
#    image: ahmedgeze/location-service:1.0
#    container_name: springbootapp
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - pgdb
#    links:
#      - pgdb
#    environment:
#          SPRING_DATASOURCE_URL:  jdbc:postgresql://postgres/postgres
